name: 'Build PostgreSQL'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: desktop

    defaults:
      run:
        shell: bash
        working-directory: docker-postgresql # <- change this to your Terraform folder

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Check Terraform formatting
    - name: Terraform Format
      run: terraform fmt -check

    # Generate Terraform plan
    - name: Terraform Plan
      run: terraform plan -input=false

    # Apply Terraform on push to main
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
